apiVersion: v1
kind: Pod       #  type of Kubernetes resource
metadata:
    name: draining-node-test-pod
    labels:
        tier: frontend
spec:           # Defines the desired state of the Pod
    containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
    restartPolicy: OnFailure